### ISSUE TITLE
UI Improvement - Copy/Paste of Application

### ISSUE THREAD

**Issue by marycrow** [SFDO-Community/GrantGuides#122] opened 2023-12-13 23:40 UTC
**OVERVIEW**

The following is from a list from the Chicago Sprint on Improvements that the group felt would be important to users:
https://salesforce.quip.com/JKMnAsPUEeDd

Add to top of page vice within sections - copy/past function

**ACCEPTANCE CRITERIA**

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

**Comment by marycrow** [comment] 2024-02-07 16:47
I'm not seeing a way to clone an entire grant application. 

![Image](https://github.com/SFDO-Community/GrantGuides/assets/35714113/0a1fac3f-e98a-4c28-90c1-2ce9d04b9fde)


![Image](https://github.com/SFDO-Community/GrantGuides/assets/35714113/7a6f21f3-f254-46f9-95e7-9383d86d0654)

**Comment by cidarm** [comment] 2024-02-15 00:54
duplicate of #119

**Closed** 2024-02-16 04:25 UTC
Labels: enhancement
